### PR TITLE
update versions and openid_connect patch

### PR DESCRIPTION
**Pull request by arnisoph**
Should replace #6

### CODE REVIEW

**Comment by arnisoph** [comment]
FYI I haven't tested the images yet. Please take a look!

https://hub.docker.com/r/inovex/gitlab/tags/

**Comment by theinrichs** [comment]
Thx @arnoldbechtoldt we'll check the new builds in the project asap :slightly_smiling_face:

**Comment by arnisoph** [comment]
Thanks, awaiting your feedback.

**Comment by arnisoph** [comment]
So..? :)

**Comment by arnisoph** [comment]
🎉

**Pull request merged**
